### ISSUE TITLE
Come join us!

### ISSUE THREAD

**Issue by ZirconiumX** [Chlorek/Colorsair#1]
Hi, I'm one of the developers of ckb-next, and we've got drivers for Corsair's keyboards, mice and the Polaris mousepad.

Perhaps we could work together on this? We've had an open issue for it for a while, and it would save you reinventing the wheel unnecessarily.

**Comment by Chlorek** [comment]
Hi, damn sure I will join you :)

**Comment by ZirconiumX** [comment]
We usually talk on IRC at #ckb-next on Freenode.

I would be on there right now but my IRC VPS is playing up.
